# 📊 Amazon Reviews Dataset Preparation

We'll begin by preprocessing the Amazon Reviews dataset from Kaggle.

In [1]:
import pandas as pd

## Explore the Data

The dataset has 3 columns:
- **label**: Polarity of the review (Negative = 0, Positive = 1)
- **title**: Title of the review
- **review**: The review itself

In [2]:
train_df = pd.read_csv('data/reviews.csv', header=0, names=['review','label'])

In [3]:
train_df.head()

                                              review  label
0  I didn't think at first that PotC would be all...      1
1  I admit, I was a bit unsure when I popped the ...      1
2  This is exactly the phone I wanted, and was so...      0
3  Sorry. No more than recylcled information, mos...      0
4  I read all of the good reviews and bought one....      0

In [4]:
train_df.shape

(60000, 2)

## Missing Values

In [5]:
train_df.isnull().value_counts()

review  label
False   False    60000
Name: count, dtype: int64

## Duplicate Values

In [6]:
train_df.duplicated().value_counts()

False    59999
True         1
Name: count, dtype: int64

### Remove Duplicates

In [7]:
train_df.drop_duplicates(inplace=True)

In [8]:
train_df.duplicated().value_counts()

False    59999
Name: count, dtype: int64

## Class Imbalances

In [9]:
train_df.head()

                                              review  label
0  I didn't think at first that PotC would be all...      1
1  I admit, I was a bit unsure when I popped the ...      1
2  This is exactly the phone I wanted, and was so...      0
3  Sorry. No more than recylcled information, mos...      0
4  I read all of the good reviews and bought one....      0

In [10]:
train_df['label'].value_counts()

label
1    30054
0    29945
Name: count, dtype: int64

### Fix Class Imbalances

In [11]:
positives = train_df[train_df['label'] == 1]\
                .sample(frac=1, random_state=1, ignore_index=True)\
                .loc[:10_000, ['review','label']]

negatives = train_df[train_df['label'] == 0]\
                .sample(frac=1, random_state=1, ignore_index=True)\
                .loc[:10_000, ['review','label']]

# Make sure same number of classes
negatives.shape == positives.shape

True

In [12]:
final_train_df = pd.concat([positives, negatives], axis=0, ignore_index=True)\
                   .sample(frac=1, random_state=1, ignore_index=True)

In [13]:
final_train_df.shape

(20002, 2)

## 🎉 Save the Dataset as CSV

Save all your data preprocessing work!

In [15]:
final_train_df.to_csv('data/cleaned_dataset.csv', index=False)